export const capacityModelData = [
  {
    hostname: "mvmpcxt6gjhfdyg",
    CPU: "52.3%",
    MEM: "32.5%",
    transaction: false,
    color: "red",
  },
  {
    hostname: "mvmpcxt6gjhfdyg",
    CPU: "10.5%",
    MEM: "4.5%",
    transaction: true,
    color: "green",
  },
  {
    hostname: "mvmpcxt6gjhfdyg",
    CPU: "2.13%",
    MEM: "14.5%",
    transaction: true,
    color: "yellow",
  },
  {
    hostname: "mvmpcxt6gjhfdyg",
    CPU: "56.3%",
    MEM: "85.5%",
    transaction: true,
    color: "red",
  },
  {
    hostname: "k0vnv9ce5r494ovu",
    CPU: "89.2%",
    MEM: "37.8%",
    transaction: true,
    color: "green",
  },
  {
    hostname: "wy53hz9ob3hg0cbw",
    CPU: "95.6%",
    MEM: "18.3%",
    transaction: true,
    color: "red",
  },
  {
    hostname: "d7scca4cuocxifzc",
    CPU: "67.5%",
    MEM: "22.6%",
    transaction: false,
    color: "yellow",
  },
  {
    hostname: "tclze3atej11ryu9",
    CPU: "69.1%",
    MEM: "89.6%",
    transaction: true,
    color: "yellow",
  },
  {
    hostname: "a1cvlh592zhtgmr2",
    CPU: "72.0%",
    MEM: "46.7%",
    transaction: true,
    color: "red",
  },
  {
    hostname: "vdpdt2iuvmpajvj0",
    CPU: "87.9%",
    MEM: "37.4%",
    transaction: true,
    color: "yellow",
  },
  {
    hostname: "u4ap54cqfqhm97wh",
    CPU: "72.3%",
    MEM: "25.2%",
    transaction: true,
    color: "red",
  },
  {
    hostname: "isx3rhptc9yn16gx",
    CPU: "100.0%",
    MEM: "12.4%",
    transaction: false,
    color: "red",
  },
  {
    hostname: "6ds1bv1cko3dqm4b",
    CPU: "19.6%",
    MEM: "64.6%",
    transaction: false,
    color: "white",
  },
  {
    hostname: "993ghdhloeyjw7w4",
    CPU: "57.6%",
    MEM: "12.1%",
    transaction: true,
    color: "yellow",
  },
  {
    hostname: "722gg6oq6eh85zm0",
    CPU: "52.7%",
    MEM: "74.3%",
    transaction: true,
    color: "yellow",
  },
  {
    hostname: "puf2j13drhltu1on",
    CPU: "33.2%",
    MEM: "30.3%",
    transaction: false,
    color: "red",
  },
  {
    hostname: "v7h13z4sg1x8ubxz",
    CPU: "46.6%",
    MEM: "76.4%",
    transaction: true,
    color: "green",
  },
  {
    hostname: "2ws8g2v2v97ojkpn",
    CPU: "77.5%",
    MEM: "44.7%",
    transaction: true,
    color: "yellow",
  },
  {
    hostname: "fzccipodxmrd2pfn",
    CPU: "82.5%",
    MEM: "49.4%",
    transaction: true,
    color: "yellow",
  },
  {
    hostname: "tnmqb3ubypyjpslm",
    CPU: "48.5%",
    MEM: "88.2%",
    transaction: false,
    color: "red",
  },
  {
    hostname: "pg7io4abkhi8molf",
    CPU: "28.2%",
    MEM: "32.1%",
    transaction: true,
    color: "green",
  },
  {
    hostname: "v2khxwc60emvwv0t",
    CPU: "52.9%",
    MEM: "46.2%",
    transaction: true,
    color: "yellow",
  },
  {
    hostname: "gdkbujm0im6syc7x",
    CPU: "7.8%",
    MEM: "54.3%",
    transaction: true,
    color: "yellow",
  },
  {
    hostname: "7fth6hmnzf4pqhfh",
    CPU: "34.5%",
    MEM: "57.8%",
    transaction: false,
    color: "red",
  },
  {
    hostname: "qyttk96bt01dlujq",
    CPU: "70.9%",
    MEM: "38.1%",
    transaction: true,
    color: "red",
  },
  {
    hostname: "okj7jrdhhb3m3c5a",
    CPU: "81.0%",
    MEM: "64.9%",
    transaction: true,
    color: "yellow",
  },
  {
    hostname: "p3pgzjhpumodypk4",
    CPU: "93.9%",
    MEM: "89.7%",
    transaction: true,
    color: "yellow",
  },
];
